### PR TITLE
now you can load object files from the command line

### PR DESCRIPTION
**Pull request by gianmaria**

### CODE REVIEW

**Comment by yellingintothefan** [comment]
Thanks for the interest. We can probably go:

```
FILE* const fobj = oload("model/%s.obj", nobj);
SDL_Surface* const fdif = sload("model/%s.bmp", nobj);
```

As the names of the objects match the diffusion files.

**Comment by gianmaria** [comment]
hi, like giving only the name of the object file to the command line?
e.g. `./gel charizard`

**Comment by yellingintothefan** [comment]
Yup, perfect

**Comment by gianmaria** [comment]
hope i have understood correctly 😄

**Pull request closed without merging**
